[workspace]
resolver = "2"
members = [
    "crates/plasmid-core",
    "crates/plasmid-format",
    "crates/plasmid-swarm",
    "crates/plasmid-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["epgeno <contact@epgeno.org>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/epgeno/plasmid"
homepage = "https://plasmid.wiki"
